# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Order',
			fields=[
				('pizza_id', models.AutoField(primary_key=True, serialize=False)),
				('customer_name', models.CharField(max_length=50)),
				('customer_address', models.CharField(max_length=100)),
				('pizza_size', models.CharField(choices=[('30', '30cm'), ('50', '50cm')], max_length=4)),
			],
			options={
				'ordering': ['customer_name'],
				'db_table': 'order',
			},
		),
	]
